### ISSUE TITLE
Feature Request Static PC Controller device type allowed to be included in ALIST Command

### ISSUE THREAD

**Issue by hellracer** [wburgers/Open-Zwave-Socket-Server#10]
Hi Willem,

I can understand why you deliberately exclude the Controller itself on ALIST command for ease of use on the user side, however in my humbly opinion i think it would be better if this is optional via Config.ini I guess?, so that we can leave this to the developer to exclude or include the controller on the device list.

my c++ is very rusty but by deleting this 3 lines of code the controller will shown in ALIST command i know our millage will vary this is just my 0.2 :), 

I know this is my bad attempt to serve my own needs :)

Main.cpp

if(nodeType == "Static PC Controller" || nodeType == "") {
					continue;
				}

**Comment by wburgers** [comment]
Hi,

The controller has been excluded since I first forked this project, so it wasn't exactly my choice.
I never had a need for seeing the controller on the client side, that is why I never changed it, but if you do, then I will support that of course :+1: 

Thanks again for your input!

**Comment by hellracer** [comment]
I stand corrected sorry if my assumption is wrong :), my personal reason why the controller need to be be included is more on an aesthetic side of things, again thanks a lot.

**Comment by wburgers** [comment]
No need to be sorry mate, I just want to make it more clear :wink:
