### ISSUE TITLE
Openzwave-Server build issue

### ISSUE THREAD

**Issue by hellracer** [wburgers/Open-Zwave-Socket-Server#13]
Hi Willem,

I try to reproduce the bug on issue  # 12 to a different computer, but I encounter a strange issue compiling Openzwave-Server, i never seen this before can you comment on this please?. I'm away on my real machine so I decided to reproduce this on a VM and I get this error.

I make sure I follow your install instruction by copy and paste but I encounter this error. 
all library has been compiled without issue except for the OWSS itself.

 

adminuser@devel:~/Open-Zwave-Socket-Server/Server$ make
g++ -c -Wall -Wno-format -g -DDEBUG -I /usr/local/include/openzwave -Wno-unknown-pragmas -o Main.o Main.cpp
Main.cpp:642:13: error: use of enum ‘libwebsocket_callback_reasons’ without previous declaration
        enum libwebsocket_callback_reasons reason,
             ^
Main.cpp:654:14: error: use of enum ‘libwebsocket_callback_reasons’ without previous declaration
         enum libwebsocket_callback_reasons reason,
              ^
Main.cpp: In function ‘int open_zwaveCallback(libwebsocket_context*, libwebsocket*, int, void*, void*, size_t)’:
Main.cpp:708:81: error: ‘libwebsockets_get_protocol’ was not declared in this scope
    libwebsocket_callback_on_writable_all_protocol(libwebsockets_get_protocol(wsi));
                                                                                 ^
Main.cpp:708:82: error: ‘libwebsocket_callback_on_writable_all_protocol’ was not declared in this scope
    libwebsocket_callback_on_writable_all_protocol(libwebsockets_get_protocol(wsi));
                                                                                  ^
Main.cpp:723:21: error: ‘libwebsocket_write’ was not declared in this scope
       LWS_WRITE_TEXT);
                     ^
Main.cpp:742:41: error: ‘libwebsockets_get_protocol’ was not declared in this scope
           libwebsockets_get_protocol(wsi));
                                         ^
Main.cpp:742:42: error: ‘libwebsocket_rx_flow_allow_all_protocol’ was not declared in this scope
           libwebsockets_get_protocol(wsi));
                                          ^
Main.cpp:744:33: error: cannot convert ‘libwebsocket*’ to ‘lws*’ for argument ‘1’ to ‘int lws_send_pipe_choked(lws*)’
     if (lws_send_pipe_choked(wsi)) {
                                 ^
Main.cpp:745:52: error: ‘libwebsocket_callback_on_writable’ was not declared in this scope
      libwebsocket_callback_on_writable(context, wsi);
                                                    ^
Main.cpp: At global scope:
Main.cpp:785:1: error: elements of array ‘libwebsocket_protocols protocols []’ have incomplete type
 };
 ^
Main.cpp:785:1: error: storage size of ‘protocols’ isn’t known
Main.cpp: In function ‘void* websockets_main(void*)’:
Main.cpp:1102:45: error: ‘libwebsocket_create_context’ was not declared in this scope
  context = libwebsocket_create_context(&info);
                                             ^
Main.cpp:1114:35: error: ‘libwebsocket_service’ was not declared in this scope
   libwebsocket_service(context, 10);
                                   ^
Main.cpp:1117:38: error: ‘libwebsocket_context_destroy’ was not declared in this scope
  libwebsocket_context_destroy(context);
                                      ^
Main.cpp: In function ‘void sigalrm_handler(int)’:
Main.cpp:2183:62: error: ‘libwebsocket_callback_on_writable_all_protocol’ was not declared in this scope
    libwebsocket_callback_on_writable_all_protocol(protocols+1);
                                                              ^
make: *** [Main.o] Error 1
adminuser@devel:~/Open-Zwave-Socket-Server/Server$

**Comment by wburgers** [comment]
Libwebsockets updated to 1.6 and gave everything a prefix of lws_ instead of libwebsocket_
Please use the latest test branch of OZWSS to fix this issue.
I will merge this into master together with your other suggestions in the upcoming holiday!

Thanks for the quick notice of this issue!
