### ISSUE TITLE
Feature request Config.ini zwxxx.xml user configurable

### ISSUE THREAD

**Issue by hellracer** [wburgers/Open-Zwave-Socket-Server#9]
Hi Willem,

I know this is very trivial stuff but I'll ask it anyway, right now both configuration has been created with the assumption where the current openzwave binary is located is it possible if we can pass some switch as argument with openzwave binary so that we can tidy this thing a little bit? 

E.g sudo openzwave-server -n /etc/openzwave

Config.ini will be look at on the specified directory whilst zwxxx.xml will be created or updated on that as well, thanks in advance and Sorry for taking so much of your time :)

**Comment by wburgers** [comment]
The path to the config.ini is indeed hardcoded now.
I'll make that an argument to the program and let you know!

Thanks for your input. I really appreciate it!
Though I don't have much time to work on this, I still like it.
I also think it is really cool other people are actually using this.
So please keep the feedback coming and we can make this an awesome server 😃.

**Comment by wburgers** [comment]
It is now possible to specify the command line option "-confPath /path/to/conf"
as the serial port was already a command line option, but was hardcoded to the first parameter, it is now a more softcoded option. You can set it with "-serialPort /dev/ttyUSB0" or whatever the port is.

Hope this is clear :-).
